import {
  accent,
  accentBg,
  accentSoft,
  bg,
  border,
  brand,
  container,
  fontDisplay,
  fontMono,
  fontSans,
  fontSansMedium,
  fonts,
  fsBody,
  fsBodyL,
  fsCaption,
  fsDisplayL,
  fsDisplayM,
  fsDisplayXl,
  fsMicro,
  fsTitle,
  layout,
  lhBody,
  lhBodyL,
  lhCaption,
  lhDisplayL,
  lhDisplayM,
  lhDisplayXl,
  lhMicro,
  lhTitle,
  motion,
  price,
  radius,
  roles,
  sale,
  shadowCard,
  shadowPop,
  shadowSheet,
  shadowSm,
  shadows,
  spacing,
  success,
  surface,
  tapTarget,
  text,
  textBody,
  textMuted,
  trackingLabel,
  trackingTight,
  trackingWide,
  typography,
  weightLight,
  weightMed,
  weightReg,
  weightSemi,
  zNav,
  zSheet,
  zToast,
} from './tokens';

export * from './tokens';

export const theme = {
  colors: {
    ...brand,
    ...roles,
  },
  fonts,
  typography: {
    ...typography,
    displayXl: {
      fontFamily: fontDisplay,
      fontSize: fsDisplayXl,
      lineHeight: fsDisplayXl * lhDisplayXl,
      letterSpacing: fsDisplayXl * trackingTight,
      color: text,
    },
    displayL: {
      fontFamily: fontDisplay,
      fontSize: fsDisplayL,
      lineHeight: fsDisplayL * lhDisplayL,
      letterSpacing: fsDisplayL * trackingTight,
      color: text,
    },
    displayM: {
      fontFamily: fontDisplay,
      fontSize: fsDisplayM,
      lineHeight: fsDisplayM * lhDisplayM,
      letterSpacing: fsDisplayM * trackingTight,
      color: text,
    },
    title: {
      fontFamily: fontSansMedium,
      fontSize: fsTitle,
      lineHeight: fsTitle * lhTitle,
      color: text,
    },
    bodyL: {
      fontFamily: fontSans,
      fontSize: fsBodyL,
      lineHeight: fsBodyL * lhBodyL,
      color: textBody,
    },
    body: {
      fontFamily: fontSans,
      fontSize: fsBody,
      lineHeight: fsBody * lhBody,
      color: textBody,
    },
    caption: {
      fontFamily: fontSans,
      fontSize: fsCaption,
      lineHeight: fsCaption * lhCaption,
      color: textBody,
    },
    micro: {
      fontFamily: fontMono,
      fontSize: fsMicro,
      lineHeight: fsMicro * lhMicro,
      color: textMuted,
    },
    label: {
      fontFamily: fontMono,
      fontSize: 10,
      letterSpacing: trackingLabel * 10,
      textTransform: 'uppercase' as const,
      color: accentSoft,
    },
    kicker: {
      fontFamily: fontMono,
      fontSize: 10,
      letterSpacing: trackingLabel * 10,
      textTransform: 'uppercase' as const,
      color: accentSoft,
    },
  },
  spacing,
  radius,
  shadows,
  motion,
  layout: {
    ...layout,
    tapTarget,
    container,
    zNav,
    zSheet,
    zToast,
  },
  semantic: {
    bg,
    surface,
    text,
    textBody,
    textMuted,
    border,
    accent,
    accentSoft,
    accentBg,
    price,
    sale,
    success,
  },
  weights: {
    light: weightLight,
    reg: weightReg,
    med: weightMed,
    semi: weightSemi,
  },
  tracking: {
    label: trackingLabel,
    wide: trackingWide,
    tight: trackingTight,
  },
  elevation: {
    sm: shadowSm,
    card: shadowCard,
    pop: shadowPop,
    sheet: shadowSheet,
  },
} as const;

export type Theme = typeof theme;
